# install required packages

install.packages("abind")
install.packages("bookdown")
install.packages("cli")
install.packages("covidcast")
install.packages("cowplot")
install.packages("data.table")
install.packages("DataExplorer")
install.packages("dplyr")
install.packages("dspline")
install.packages("geofacet")
install.packages("ggnewscale")
install.packages("here")
install.packages("KFAS")
install.packages("knitr")
install.packages("lubridate")
install.packages("Matrix")
install.packages("methods")
install.packages("mgcv")
install.packages("nnet")
install.packages("patchwork")
install.packages("Rcpp")
install.packages("readr")
install.packages("remotes")
install.packages("reshape")
install.packages("reshape2")
install.packages("reticulate")
install.packages("rlang")
install.packages("rmarkdown")
install.packages("scales")
install.packages("stringr")
install.packages("tidyverse")
install.packages("tsibble")
install.packages("usdata")
install.packages("usmap")
install.packages("viridisLite")
install.packages("zoo")


remotes::install_github("cmu-delphi/epiprocess")
remotes::install_github("cmu-delphi/epidatr")
