---
title: "Flow chart bits"
author: "DJM"
date: "14 May 2024"
output: pdf_document
    
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, 
  message = FALSE, 
  echo = FALSE,
  fig.path = here::here("gfx/"),
  fig.width = 4,
  fig.height = 3,
  dev = "svg"
)
```

```{r load-packages}
library(tidyverse)
library(here)
library(cowplot)
```

```{r load-data}
adj_df_list <- readRDS(here("data", "adj_df_list_F24.rds"))
adj_df <- bind_rows(adj_df_list)
pop <- read_rds(here("data", "pop_df.RDS")) |>
  filter(geo_value == "NJ") |> 
  pull(population_2020) / 1e5
state_decon_byvar_df <- read_rds(here("data", "NJ-state_decon_byvar_df.rds"))
deconv_cases <- read_rds(here("data", "NJ-final-thetas-pr.rds"))
deconv_cases <- tibble(
  deconv_cases = deconv_cases, 
  time_value = seq(ymd("2020-03-01"), ymd("2023-03-01"), by = "1 day")
)

dat <- adj_df |>
  rename(time_value = date) |>
  filter(geo_value == "NJ", time_value >= ymd("2020-09-01"), 
         time_value <= ymd("2021-06-01")) |>
  select(time_value, geo_value, adj_inf_rate, unadj_inf_rate, cases_rate_7d_av,
         ninetyfive_lowb_rate, ninetyfive_upb_rate, eighty_lowb_rate,
         eighty_upb_rate, fifty_lowb_rate, fifty_upb_rate) |>
  as_tibble() |>
  left_join(deconv_cases, by = "time_value") |>
  left_join(
    state_decon_byvar_df |> 
      select(variant, time_value, geo_value, infect_rate) |>
      filter(variant %in% c("Iota", "Other")),
    by = join_by(time_value, geo_value)
  ) |>
  pivot_wider(names_from = variant, values_from = infect_rate)
```


```{r step1}
s1 <- dat |>
  ggplot(aes(time_value)) +
  geom_line(aes(y = cases_rate_7d_av), color = "grey75", linewidth = 1) +
  geom_line(aes(y = deconv_cases / pop), color = "red3", linewidth = 1) +
  scale_x_date(expand = expansion()) + 
  scale_y_continuous(expand = expansion(), breaks = 1:5 * 25) +
  coord_cartesian(xlim = ymd(c("2020-09-01","2021-05-01")), ylim = c(0, 125)) +
  theme_minimal() + ggtitle("Step 1") +
  theme(
    legend.position = "none", 
    axis.line = element_line(colour = "black", linewidth = 1),
    axis.text = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title = element_blank(),
    title = element_text(face = "bold", size = 20)
  )
ggdraw(s1) + 
  draw_label(
    "Deconvolve reported cases\nto positive specimen\ncollection date.",
    x = 0.05, y = 0.8, hjust = 0, vjust = 1, size = 16
  )
```

```{r step2}
s2 <- dat |>
  ggplot(aes(time_value)) +
  geom_line(aes(y = cases_rate_7d_av), color = "grey90", linewidth = 1) +
  geom_line(aes(y = deconv_cases / pop), color = "grey75", linewidth = 1) +
  geom_line(aes(y = Other), colour = "mediumseagreen", linewidth = 1) + 
  geom_line(aes(y = Iota), colour = "mediumpurple", linewidth = 1) + 
  scale_x_date(expand = expansion()) + 
  scale_y_continuous(expand = expansion(), breaks = 1:5 * 25) +
  coord_cartesian(xlim = ymd(c("2020-09-01","2021-05-01")), ylim = c(0, 125)) +
  theme_minimal() + ggtitle("Step 2") +
  theme(
    legend.position = "none", 
    axis.line = element_line(colour = "black", linewidth = 1),
    axis.text = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title = element_blank(),
    title = element_text(face = "bold", size = 20)
  )
ggdraw(s2) + 
  draw_label(
    "Deconvolve positive specimen\ndate to infection onset date,\nseparately per variant.",
    x = 0.05, y = 0.8, hjust = 0, vjust = 1, size = 16
  )
```

```{r step3}
s3 <- dat |>
  ggplot(aes(time_value)) +
  geom_line(aes(y = cases_rate_7d_av), color = "grey90", linewidth = 1) +
  geom_line(aes(y = deconv_cases / pop), color = "grey90", linewidth = 1) +
  geom_line(aes(y = Other), colour = "grey75", linewidth = 1) + 
  geom_line(aes(y = Iota), colour = "grey75", linewidth = 1) + 
  geom_line(aes(y = unadj_inf_rate), colour = "orange", linewidth = 1) +
  scale_x_date(expand = expansion()) + 
  scale_y_continuous(expand = expansion(), breaks = 1:5 * 25) +
  coord_cartesian(xlim = ymd(c("2020-09-01","2021-05-01")), ylim = c(0, 125)) +
  theme_minimal() + ggtitle("Step 3") +
  theme(
    legend.position = "none", 
    axis.line = element_line(colour = "black", linewidth = 1),
    axis.text = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title = element_blank(),
    title = element_text(face = "bold", size = 20)
  )
  
ggdraw(s3) + 
  draw_label(
    "Sum per-variant infection\nonset curves to produce\naggregate onset curve.",
    x = 0.05, y = 0.8, hjust = 0, vjust = 1, size = 16
  )
```


```{r step4}
#| fig-height: 7.75
s4 <- dat |> 
  ggplot(aes(time_value)) + 
  geom_line(aes(y = cases_rate_7d_av), color = "grey90", linewidth = 1) +
  geom_line(aes(y = deconv_cases / pop), color = "grey90", linewidth = 1) +
  geom_line(aes(y = Other), colour = "grey90", linewidth = 1) + 
  geom_line(aes(y = Iota), colour = "grey90", linewidth = 1) + 
  geom_line(aes(y = unadj_inf_rate), colour = "grey75", linewidth = 1) +
  geom_ribbon(aes(ymin = ninetyfive_lowb_rate, ymax = ninetyfive_upb_rate), 
              fill = "lightskyblue1") +
  geom_ribbon(aes(ymin = eighty_lowb_rate, ymax = eighty_upb_rate), 
              fill = "lightskyblue") +
  geom_ribbon(aes(ymin = fifty_lowb_rate, ymax = fifty_upb_rate), 
              fill = "skyblue3") +
  geom_line(aes(y = adj_inf_rate), color = "midnightblue", linewidth = 1) +
  scale_x_date(expand = expansion()) + 
  scale_y_continuous(expand = expansion(), breaks = 1:15 * 25) +
  coord_cartesian(xlim = ymd(c("2020-09-01","2021-05-01")), ylim = c(0, 375)) +
  theme_minimal() + ggtitle("Step 4") +
  theme(
    legend.position = "none", 
    axis.line = element_line(colour = "black", linewidth = 1),
    axis.text = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title = element_blank(),
    title = element_text(face = "bold", size = 20)
  )

ggdraw(s4) + 
  draw_label(
    "Scale aggregate curve by the\ninverse reporting ratio.",
    x = 0.05, y = 0.93, hjust = 0, vjust = 1, size = 16
  )
```
